//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmaniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank
    {
        public bank()
        {
            this.bank_branch = new HashSet<bank_branch>();
        }
    
        public int code { get; set; }
        public string Name { get; set; }
        public string Addresss { get; set; }
    
        public virtual ICollection<bank_branch> bank_branch { get; set; }
    }
}
