//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmaniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_branch
    {
        public bank_branch()
        {
            this.accounts = new HashSet<account>();
            this.customers = new HashSet<customer>();
            this.loans = new HashSet<loan>();
        }
    
        public int Bank_Branch_id { get; set; }
        public string Address { get; set; }
        public Nullable<int> code { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual bank bank { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<loan> loans { get; set; }
    }
}
