//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmaniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int LoanNo { get; set; }
        public int Amount { get; set; }
        public string type { get; set; }
        public Nullable<int> Bank_Branch_id { get; set; }
    
        public virtual bank_branch bank_branch { get; set; }
    }
}
